hostNetwork: true
hostPID: true

service:
  enabled: false

rbac:
  create: true

serviceAccount:
  create: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
